services:
  api1:
    image: ghcr.io/alexoliveiramartins/fraud-detection:0df7bb5e6c92b9d65902c254348ee46d60c82446
    hostname: api1
    platform: linux/amd64
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"

  api2:
    image: ghcr.io/alexoliveiramartins/fraud-detection:0df7bb5e6c92b9d65902c254348ee46d60c82446
    hostname: api2
    platform: linux/amd64
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"

  haproxy:
    image: haproxy:3.0-alpine
    hostname: haproxy
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  fraud-network:
    driver: bridge
