FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

COPY cmd ./cmd
COPY internal ./internal

RUN GOAMD64=v3 GOMAXPROCS=1 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o fraud-detection ./cmd/api

FROM scratch

WORKDIR /app

COPY --from=builder /app/fraud-detection .
COPY resources/ivf ./resources/ivf
COPY resources/mcc_risk.json ./resources/mcc_risk.json
COPY resources/normalization.json ./resources/normalization.json

EXPOSE 8080

CMD ["./fraud-detection"]
